# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Windows Release Build

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build exe
      run: .\build.bat

    - name: Create release bundle
      run: |
        mkdir release
        copy dist\k400p-fn-lock.exe release\
        copy README.md release\
        copy LICENSE release\
        powershell Compress-Archive -Path release\* -DestinationPath k400p-fn-lock-win-${{ github.ref_name }}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: k400p-fn-lock-win-release
        path: release\

    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        files: k400p-fn-lock-win-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
